# obs/workflows/render-obs.yaml
name: Render Prometheus Manifest

on:
  push:
    branches: ["main"]
    paths:
      - "obs/prometheus/**"
      - "obs/workflows/render-obs.yaml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render-prometheus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Add Helm repo
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Render kube-prometheus-stack
        run: |
          mkdir -p obs/prometheus/deploy
          helm template prometheus prometheus-community/kube-prometheus-stack \
            -n monitoring \
            -f obs/prometheus/deploy/kps.values.yaml \
            > obs/prometheus/deploy/prometheus.yaml

      - name: Commit & Push (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add obs/prometheus/deploy/prometheus.yaml

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "chore(obs): render prometheus manifest"
          git push
